// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoRoRISPFeW2qRN-Dh5hHHvDWe3IpJJ28',
    appId: '1:638585044150:web:486dd587494e6925093a17',
    messagingSenderId: '638585044150',
    projectId: 'izerak-79b81',
    authDomain: 'izerak-79b81.firebaseapp.com',
    storageBucket: 'izerak-79b81.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-EbOlBfdIGdbkJRtfyPLsME2D-_dY-9Y',
    appId: '1:638585044150:android:3a09666e56db2d58093a17',
    messagingSenderId: '638585044150',
    projectId: 'izerak-79b81',
    storageBucket: 'izerak-79b81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8lSIMubNOI_pHvzhw7wcOlUyYW-Xe35c',
    appId: '1:638585044150:ios:527c6bc51d7cb036093a17',
    messagingSenderId: '638585044150',
    projectId: 'izerak-79b81',
    storageBucket: 'izerak-79b81.appspot.com',
    iosBundleId: 'com.example.iZerakApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8lSIMubNOI_pHvzhw7wcOlUyYW-Xe35c',
    appId: '1:638585044150:ios:9b40593901a278f1093a17',
    messagingSenderId: '638585044150',
    projectId: 'izerak-79b81',
    storageBucket: 'izerak-79b81.appspot.com',
    iosBundleId: 'com.example.iZerakApp.RunnerTests',
  );
}
